### PR TITLE
FIFA 23 support

### PR DESCRIPTION
**Pull request by francoism90**
I hope you can help me, it would be great to add FIFA 23 support. :)

Questions:
- The profile doesn't seem to load, how should one debug this? Can I see what parsing goes wrong?
- How to compile a FIFA23SDK.dll? I understand if you cannot share every detail about this.

Thanks!

### CODE REVIEW

**Comment by wannkunstbeikor** [comment]
i will add it if i have time to generate the sdk, but currently i have some stuff to do and im not gonna explain u every single step, but from what u saw u have the wrong oodle version and everything else is probably related to u not having the sdk

**Comment by francoism90** [comment]
@wannkunstbeikor Thanks for your reply, and I understand it will take some time. :)

Just one question: is it possible to get/dump debug info? I'm only seeing 'There was an error..', but no other info. I'm new to this, but willing to learn and contribute.

**Comment by wannkunstbeikor** [comment]
if u mean the sdk creation, that generates a errors.txt file in the frosty install folder

**Comment by wannkunstbeikor** [comment]
u can also comment out the line that deletes the temp.cs file to look at that

**Comment by francoism90** [comment]
@wannkunstbeikor Thanks!

I've uncomment temp.cs, but nothing happens. It doesn't seem the FIFA 23 is added to the profiles list. Is there something I need to building that list? It doesn't seem Profile.bin get's populated.

**Comment by francoism90** [comment]
Succes! I needed to run FrostyCmd. Now it's telling me the SDK is out-of-dated. Checking..

Edit: not able to perform the second step, it finds the process, but maybe EA's (stupid) anticheat is causing it to fail?

**Comment by francoism90** [comment]
@wannkunstbeikor Almost! Could you give me a tip how to find the first type offset?

It now crashes when building the SDK, I don't think I have the correct address.

Unhandled Exception: System.ArgumentException: An item with the same key has already been added.

**Comment by wannkunstbeikor** [comment]
if u already have an offset, u can just use the previous offset to go to the start of the typeinfo

**Comment by francoism90** [comment]
@wannkunstbeikor I don't think I've the correct one? It found one result and then FrostEditor crashed at the last step. Is this normal? Should it start with FifaData or something?

Thanks

**Comment by francoism90** [comment]
@wannkunstbeikor If I uncomment the following line, it seems to start scanning:
```
// m_offsetClassInfoMappings.Add(origOffset, info);
```

**Pull request closed without merging**
