### PR TITLE
[Plugins] Fixed platform launcher failing to run Steam games with mods

### PR DESCRIPTION
**Pull request by t3m1X**
PlatformLauncher plugin would get stuck waiting for the platform and/or game to launch and would fail to set env variable properly for Steam and Epic Games Store.
These changes make games in these platforms now launch reliably with mods, as well as adds an extra option to the plugin configuration just for user comfort.

### CODE REVIEW

**Comment by wannkunstbeikor** [comment]
You should follow the CodingStandards, even if the original code didnt

**Comment by t3m1X** [comment]
That is my bad, am used to keeping with whatever code style was used, I will go through it in a minute and change it to follow C# Standards

**Comment by wannkunstbeikor** [comment]
I meant the standards cade put into a file in FrostyCore/CodingStandards

**Comment by t3m1X** [comment]
Ah, I did miss that file (I believe it is not on branch 1.0.6.2), thank you for pointing it out, I will comb the file again. 

May I ask have [.editorconfig](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/code-style-rule-options?view=vs-2022) been considered, since the project uses VS-2022?

**Comment by wannkunstbeikor** [comment]
Diana made a pr for that #121

**Pull request merged**
