### PR TITLE
Adds multiple new profiles

### PR DESCRIPTION
**Pull request by wannkunstbeikor**
- Adds Fifa 21/22 profile
- Adds Madden 22/23 profile
- Adds Battlefield 2042 profile
- Adds new RiffEbxReader, based on the one from [beb731](https://github.com/bep713/FrostyToolsuite/blob/madden22-profile/FrostySdk/IO/EbxReader.cs)
- Reworks CasAssetLoader, merges Pvz- and AnthemAssetLoader and improves it
- Splits EbxReader into different files

### CODE REVIEW

**Comment by francoism90** [comment]
@wannkunstbeikor Sorry for asking, ignore if you don't want to answer. :)

I was looking at this PR and I noticed `CreateFifa23Profile`, but it doesn't seem to be connected yet as a profile. Is this true? Would it be possible to test FIFA 23 using the FrostyToolsuite by just making the connection myself?

Thanks for making this open-source, it's really nice to see how this tool is actually build and how it works. :+1:

**Comment by wannkunstbeikor** [comment]
yeah its pretty similar to the other games, only issue is the sdk, i tried generating it the same way u would do with eac, but that didnt work so i gave up, bc i dont really care about fifa

**Comment by wannkunstbeikor** [comment]
tho it wont work without changing some stuff, since iirc it uses a new version of oodle

**Comment by francoism90** [comment]
@wannkunstbeikor It seems @paulov-t got it working: https://github.com/paulov-t/FrostbiteModdingTool

**Comment by wannkunstbeikor** [comment]
yeah ik

**Pull request merged**
