### PR TITLE
Fix titlecase to match other Task Window logs

### PR DESCRIPTION
**Pull request by Dyvinia**
keeps consistency with other messages in Frosty Task Window

### CODE REVIEW

**Comment by Dyvinia** [comment]
wait

**Comment by chromKa** [comment]
why too many updates for OLD 1.0.6, if more expected version 2.0? Maybe 1.0.6 will become outdated?

**Comment by Dyvinia** [comment]
?

**Comment by chromKa** [comment]
> ?

I'm just wondering why update the old version and waste time on it when everyone is waiting for version 2.0

**Comment by Dyvinia** [comment]
> > ?
> 
> I'm just wondering why update the old version and waste time on it when everyone is waiting for version 2.0

because bug fixes are a thing. also porting 107 features since 107 is dead.

**Comment by chromKa** [comment]
> > > ?
> > 
> > 
> > I'm just wondering why update the old version and waste time on it when everyone is waiting for version 2.0
> 
> because bug fixes are a thing. also porting 107 features since 107 is dead.

Ok, but nfs unbound will be supported in 1.0.6.3?

**Comment by Dyvinia** [comment]
not up to me, nor would it be something for me to do

**Pull request merged**
