### PR TITLE
Squadrons profile and small fixes

### PR DESCRIPTION
**Pull request by CosmicDreamsOfCode**
Fixed up and enabled the SWS profile a little with a hacky solution to a shader problem for now.
Also fixed BFV's read-only status and default values for performance variation loading.

### CODE REVIEW

**Comment by CosmicDreamsOfCode** [comment]
Bundle names are weird so closing for now,

**Comment by CosmicDreamsOfCode** [comment]
It was just the cache being weird.

**Comment by CosmicDreamsOfCode** [comment]
Another note: it crashes when going to the variations tab on SWS meshes. Not sure why.

**Comment by CosmicDreamsOfCode** [comment]
Conflicts should be fixed.

**Comment by davesarmoury** [comment]
First, love that this is being done.  I am working on a fairly large project, and this will be key to making that happen.  Open to working together if you are interested.

Anyway, I built this PR from source, and everything starts up fine, but when updating the SDK, it finds the launcher, then fails on "Scanning for type into offset".  Any ideas?  I couldn't find anything on the discord

**Comment by CosmicDreamsOfCode** [comment]
> First, love that this is being done. I am working on a fairly large project, and this will be key to making that happen. Open to working together if you are interested.
> 
> Anyway, I built this PR from source, and everything starts up fine, but when updating the SDK, it finds the launcher, then fails on "Scanning for type into offset". Any ideas? I couldn't find anything on the discord

So what's happening is that the game uses Easy Anti Cheat
You need to bypass it to generate an SDK.
I included a pre-generated one on the repo though in the same place all the other ones are however so you shouldn't have to generate one.

Also because it uses EAC, and due to my lack of knowledge on coding or whatever this is read-only unfortunately.

**Comment by Alcom1** [comment]
> Also because it uses EAC, and due to my lack of knowledge on coding or whatever this is read-only unfortunately.

You can disable EAC by just renaming the executable.

I had to rebuild the squadrons profile for **starwarssquadrons_launcher.exe** instead of **starwarssquadrons.exe**, but was able to build an sdk and view the editor.

**Comment by Alcom1** [comment]
Besides EAC shenanigans, what is required to make Squadrons support _not_ read-only?

**Comment by CosmicDreamsOfCode** [comment]
> Besides EAC shenanigans, what is required to make Squadrons support _not_ read-only?

It needs a writer for the specific layout this game and BFV use.

**Comment by CosmicDreamsOfCode** [comment]
I'm gonna redo my fork to make this PR a lot cleaner. Closing.

**Pull request closed without merging**
